
import React from 'react'
import '@styles/globals.css';
import Nav from '@components/Nav';
import Provider from '@components/Provider';


export const metadata={
  title:"Promptopia",
  description:'discover & share ai prompts'
}
const RootLayout = ({ children }) => {
  return (
    <html>
      <body>
        <Provider>
        <div className="main">
          <div className="gradient"/>
        </div>
            <main className="app">
              <Nav/>
              {/* <Provider/> */}
              {children}
            </main>
        </Provider>
      </body>
    </html>
  )
}

export default RootLayout


// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
